[package]
name = "fast-insight-engine"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2.108"
js-sys = "0.3.85"

ndarray = { version = "0.17.2", features = ["serde"] }

linfa = { version = "0.8.1", features = ["isofit", "clustering", "linear"] }

getrandom = { version = "0.3.4", features = ["wasm_js"] } # Wasm 环境下随机数支持
